

DROP VIEW IF EXISTS vista_solicitudes CASCADE;
DROP TABLE IF EXISTS notificaciones CASCADE;
DROP TABLE IF EXISTS donaciones CASCADE;
DROP TABLE IF EXISTS solicitudes CASCADE;
DROP TABLE IF EXISTS donantes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS estados_solicitud CASCADE;
DROP TABLE IF EXISTS grupos_sanguineos CASCADE;
DROP TABLE IF EXISTS roles CASCADE;


CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

CREATE TABLE grupos_sanguineos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE estados_solicitud (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    telefono VARCHAR(30),
    ciudad VARCHAR(100),
    fecha_nacimiento DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (rol_id)
        REFERENCES roles(id)
);

CREATE TABLE donantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    grupo_sanguineo_id BIGINT NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    ultima_donacion DATE,
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_donante_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_donante_grupo
        FOREIGN KEY (grupo_sanguineo_id)
        REFERENCES grupos_sanguineos(id)
);

CREATE TABLE solicitudes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    grupo_sanguineo_id BIGINT NOT NULL,
    estado_id BIGINT NOT NULL,
    nombre_paciente VARCHAR(150) NOT NULL,
    cantidad_donantes INTEGER NOT NULL,
    hospital VARCHAR(150) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    fecha_necesidad DATE,
    descripcion TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_solicitud_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_solicitud_grupo
        FOREIGN KEY (grupo_sanguineo_id)
        REFERENCES grupos_sanguineos(id),
    CONSTRAINT fk_solicitud_estado
        FOREIGN KEY (estado_id)
        REFERENCES estados_solicitud(id),
    CONSTRAINT chk_cantidad_donantes
        CHECK (cantidad_donantes > 0)
);

CREATE TABLE donaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donante_id BIGINT NOT NULL,
    solicitud_id BIGINT NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'registrada',
    fecha_donacion DATE,
    observaciones TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_donacion_donante
        FOREIGN KEY (donante_id)
        REFERENCES donantes(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_donacion_solicitud
        FOREIGN KEY (solicitud_id)
        REFERENCES solicitudes(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_estado_donacion
        CHECK (
            estado IN ('registrada', 'confirmada', 'realizada', 'cancelada')
        ),
    CONSTRAINT uq_donante_solicitud
        UNIQUE (donante_id, solicitud_id)
);

CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    tipo VARCHAR(50),
    solicitud_id BIGINT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_notificacion_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notificacion_solicitud
        FOREIGN KEY (solicitud_id)
        REFERENCES solicitudes(id)
        ON DELETE SET NULL
);

INSERT INTO roles (nombre, descripcion)
VALUES
    ('DONANTE', 'Usuario registrado como donante'),
    ('SOLICITANTE', 'Usuario que puede crear solicitudes'),
    ('ADMIN', 'Administrador del sistema');

INSERT INTO grupos_sanguineos (nombre)
VALUES
    ('A+'),
    ('A-'),
    ('B+'),
    ('B-'),
    ('AB+'),
    ('AB-'),
    ('O+'),
    ('O-');

INSERT INTO estados_solicitud (nombre, descripcion)
VALUES
    ('ACTIVA', 'La solicitud está buscando donantes'),
    ('EN_PROCESO', 'La solicitud está siendo atendida'),
    ('COMPLETADA', 'La cantidad de donantes fue completada'),
    ('CANCELADA', 'La solicitud fue cancelada');

CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_ciudad ON usuarios(ciudad);
CREATE INDEX idx_donantes_grupo ON donantes(grupo_sanguineo_id);
CREATE INDEX idx_donantes_disponible ON donantes(disponible);
CREATE INDEX idx_solicitudes_grupo ON solicitudes(grupo_sanguineo_id);
CREATE INDEX idx_solicitudes_estado ON solicitudes(estado_id);
CREATE INDEX idx_solicitudes_ciudad ON solicitudes(ciudad);
CREATE INDEX idx_solicitudes_fecha ON solicitudes(fecha_necesidad);
CREATE INDEX idx_donaciones_donante ON donaciones(donante_id);
CREATE INDEX idx_donaciones_solicitud ON donaciones(solicitud_id);
CREATE INDEX idx_notificaciones_usuario ON notificaciones(usuario_id);

CREATE VIEW vista_solicitudes AS
SELECT
    s.id,
    s.nombre_paciente,
    gs.nombre AS grupo_sanguineo,
    es.nombre AS estado,
    s.cantidad_donantes,
    s.hospital,
    s.ciudad,
    s.fecha_necesidad,
    s.descripcion,
    s.creado_en,
    u.nombre AS solicitante
FROM solicitudes s
INNER JOIN grupos_sanguineos gs
    ON s.grupo_sanguineo_id = gs.id
INNER JOIN estados_solicitud es
    ON s.estado_id = es.id
INNER JOIN usuarios u
    ON s.usuario_id = u.id;


ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos_sanguineos ENABLE ROW LEVEL SECURITY;
ALTER TABLE estados_solicitud ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE donantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE solicitudes ENABLE ROW LEVEL SECURITY;
ALTER TABLE donaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificaciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY roles_select ON roles FOR SELECT USING (true);
CREATE POLICY grupos_select ON grupos_sanguineos FOR SELECT USING (true);
CREATE POLICY estados_select ON estados_solicitud FOR SELECT USING (true);
CREATE POLICY usuarios_select ON usuarios FOR SELECT USING (true);
CREATE POLICY usuarios_insert ON usuarios FOR INSERT WITH CHECK (true);
CREATE POLICY usuarios_update ON usuarios FOR UPDATE USING (true);
CREATE POLICY donantes_select ON donantes FOR SELECT USING (true);
CREATE POLICY donantes_insert ON donantes FOR INSERT WITH CHECK (true);
CREATE POLICY donantes_update ON donantes FOR UPDATE USING (true);
CREATE POLICY solicitudes_select ON solicitudes FOR SELECT USING (true);
CREATE POLICY solicitudes_insert ON solicitudes FOR INSERT WITH CHECK (true);
CREATE POLICY donaciones_select ON donaciones FOR SELECT USING (true);
CREATE POLICY donaciones_insert ON donaciones FOR INSERT WITH CHECK (true);
CREATE POLICY notificaciones_select ON notificaciones FOR SELECT USING (true);
CREATE POLICY notificaciones_insert ON notificaciones FOR INSERT WITH CHECK (true);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON vista_solicitudes TO anon, authenticated;
GRANT SELECT ON roles, grupos_sanguineos, estados_solicitud TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON usuarios, donantes, solicitudes, donaciones, notificaciones TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
