-- ============================================================
-- SANGRESOLIDARIA — CHAT DONANTE / RECEPTOR
-- Ejecutá ESTE script en el SQL Editor de Supabase.
-- NO borra tablas existentes. El chat se desbloquea
-- cuando un donante ofrece donar para una solicitud.
-- ============================================================

CREATE TABLE IF NOT EXISTS conversaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donacion_id BIGINT NOT NULL UNIQUE,
    solicitud_id BIGINT NOT NULL,
    donante_usuario_id BIGINT NOT NULL,
    receptor_usuario_id BIGINT NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_conv_donacion
        FOREIGN KEY (donacion_id)
        REFERENCES donaciones(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_conv_solicitud
        FOREIGN KEY (solicitud_id)
        REFERENCES solicitudes(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_conv_donante_usuario
        FOREIGN KEY (donante_usuario_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_conv_receptor_usuario
        FOREIGN KEY (receptor_usuario_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_conv_distintos
        CHECK (donante_usuario_id <> receptor_usuario_id)
);

CREATE TABLE IF NOT EXISTS mensajes_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversacion_id BIGINT NOT NULL,
    remitente_id BIGINT NOT NULL,
    cuerpo TEXT NOT NULL,
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_mensaje_conversacion
        FOREIGN KEY (conversacion_id)
        REFERENCES conversaciones(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_mensaje_remitente
        FOREIGN KEY (remitente_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_mensaje_cuerpo
        CHECK (char_length(trim(cuerpo)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_conversaciones_donante
    ON conversaciones (donante_usuario_id);

CREATE INDEX IF NOT EXISTS idx_conversaciones_receptor
    ON conversaciones (receptor_usuario_id);

CREATE INDEX IF NOT EXISTS idx_mensajes_conversacion
    ON mensajes_chat (conversacion_id, creado_en);

ALTER TABLE notificaciones
    ADD COLUMN IF NOT EXISTS conversacion_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_notificacion_conversacion'
    ) THEN
        ALTER TABLE notificaciones
            ADD CONSTRAINT fk_notificacion_conversacion
            FOREIGN KEY (conversacion_id)
            REFERENCES conversaciones(id)
            ON DELETE SET NULL;
    END IF;
END $$;

ALTER TABLE conversaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE mensajes_chat ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS conversaciones_select ON conversaciones;
DROP POLICY IF EXISTS conversaciones_insert ON conversaciones;
DROP POLICY IF EXISTS conversaciones_update ON conversaciones;
DROP POLICY IF EXISTS mensajes_chat_select ON mensajes_chat;
DROP POLICY IF EXISTS mensajes_chat_insert ON mensajes_chat;
DROP POLICY IF EXISTS mensajes_chat_update ON mensajes_chat;

CREATE POLICY conversaciones_select ON conversaciones FOR SELECT USING (true);
CREATE POLICY conversaciones_insert ON conversaciones FOR INSERT WITH CHECK (true);
CREATE POLICY conversaciones_update ON conversaciones FOR UPDATE USING (true);
CREATE POLICY mensajes_chat_select ON mensajes_chat FOR SELECT USING (true);
CREATE POLICY mensajes_chat_insert ON mensajes_chat FOR INSERT WITH CHECK (true);
CREATE POLICY mensajes_chat_update ON mensajes_chat FOR UPDATE USING (true);

GRANT SELECT, INSERT, UPDATE ON conversaciones, mensajes_chat, notificaciones TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
